# Generated by Django 2.2.5 on 2019-09-07 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Upload an Image', upload_to='', verbose_name='Image')),
                ('image_type', models.CharField(choices=[('SRC', 'Source'), ('DST', 'Destination'), ('WPT', 'Waypoint'), ('STA', 'Static')], max_length=3)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_name', models.TextField(blank=True, default='Retrieving...', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.CharField(blank=True, default='Calculating...', max_length=250, null=True)),
                ('path_coords', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRS', 'Processing'), ('COM', 'Complete'), ('ERR', 'Error')], default='PRS', max_length=3)),
                ('errors', models.TextField(blank=True, null=True)),
                ('destination_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_destination_image', to='service_app.ImageModel')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_source_image', to='service_app.ImageModel')),
                ('static_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_static_map', to='service_app.ImageModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waypoint_images', models.ManyToManyField(related_name='job_waypoint_images', to='service_app.ImageModel')),
            ],
        ),
    ]
