# Generated by Django 2.2.5 on 2019-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(help_text='Upload an Image', upload_to='', verbose_name='Image'),
        ),
    ]
