# Generated by Django 2.2.5 on 2019-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
