# Generated by Django 2.2.5 on 2019-09-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_auto_20190906_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='lng',
            new_name='longitude',
        ),
    ]
