# Generated by Django 2.2.5 on 2019-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_auto_20190907_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='place_name',
            field=models.TextField(blank=True, default='Retrieving...', null=True),
        ),
    ]
