# Generated by Django 2.2.5 on 2019-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_auto_20190907_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='total_distance',
            field=models.CharField(blank=True, default='Calculating...', max_length=250, null=True),
        ),
    ]
