# Generated by Django 2.2.5 on 2019-09-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_auto_20190907_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='path_coords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
