# Generated by Django 2.2.5 on 2019-09-07 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_jobmodel_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='static_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.ImageModel'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='images',
            field=models.ManyToManyField(related_name='jobs', to='service_app.ImageModel'),
        ),
    ]
