# Generated by Django 2.2.5 on 2019-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_jobmodel_path_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_type',
            field=models.CharField(choices=[('SRC', 'Source'), ('DST', 'Destination'), ('WPT', 'Waypoint'), ('STA', 'Static')], max_length=3),
        ),
    ]
