# Generated by Django 2.2.5 on 2019-09-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_auto_20190907_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='route',
            new_name='route_gps_coords',
        ),
    ]
