# Generated by Django 2.2.5 on 2019-09-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_auto_20190907_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='route_gps_coords',
        ),
    ]
