# Generated by Django 2.2.5 on 2019-09-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_auto_20190907_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='place_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
