# Generated by Django 2.2.5 on 2019-09-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_imagemodel_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='destination_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_destination_image', to='service_app.ImageModel'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='source_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_source_image', to='service_app.ImageModel'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='waypoint_images',
            field=models.ManyToManyField(related_name='job_waypoint_images', to='service_app.ImageModel'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='place_name',
            field=models.TextField(blank=True, default='YET_TO_RETRIEVE', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='static_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_static_map', to='service_app.ImageModel'),
        ),
    ]
