# Generated by Django 2.2.5 on 2019-09-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_auto_20190907_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
