# Generated by Django 2.2.5 on 2019-09-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_jobmodel_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='images',
        ),
    ]
